<?php

echo "<html>\n";
echo "  <head>\n";
echo "    <link href=\"https://fonts.googleapis.com/css?family=Playfair+Display:400,700|Roboto+Slab:300,400\" rel=\"stylesheet\">\n";
echo "    <link rel=\"stylesheet\" type=\"text/css\" href=\"reset.css\" media=\"screen\" />\n";
echo "    <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\" media=\"screen\" />\n";
echo "  </head>\n";
echo "\n";
echo "  <body>\n";
echo "    <div id = \"app\">\n";
echo "\n";
echo "      <div class=\"headLine\">\n";
echo "       <img src=\"https://content.codecademy.com/courses/learn-css-grid/project-iii/media/group-2.png\">\n";
echo "        <p> An architecture blog </p>\n";
echo "      </div>\n";
echo "\n";
echo "      <!-- the grid -->\n";
echo "      <div class=\"grid\">\n";
echo "        <!--   section 1 -->\n";
echo "        <div class=\"box a\">\n";
echo "          <img  src=\"https://content.codecademy.com/courses/learn-css-grid/project-iii/media/pexels-big.jpg\">\n";
echo "        </div>\n";
echo "        <div class=\"box b title\">\n";
echo "          Repurposed Living\n";
echo "        </div>\n";
echo "        <div class=\"box c\">\n";
echo "          Bassicarella Architectes, Hamburg, Germany Repurposed Housing\n";
echo "        </div>\n";
echo "\n";
echo "        <!--   section 2 -->\n";
echo "        <div class=\"box d\">\n";
echo "          <img  src = \"https://content.codecademy.com/courses/learn-css-grid/project-iii/media/pexels-2.jpg\">\n";
echo "        </div>\n";
echo "        <div class=\"box e title\">\n";
echo "          Angles de Pyramid Interiors\n";
echo "        </div>\n";
echo "        <div class=\"box f\">\n";
echo "          Bassicarella Architectes,\n";
echo "          Madrid, Spain\n";
echo "          Office Building\n";
echo "        </div>\n";
echo "\n";
echo "        <!--   section 3-->\n";
echo "        <div class=\"box g\">\n";
echo "          <img  src = \"https://content.codecademy.com/courses/learn-css-grid/project-iii/media/pexels-3.jpg\">\n";
echo "        </div>\n";
echo "        <div class=\"box h title\">\n";
echo "          Intricate Patter Play\n";
echo "        </div>\n";
echo "        <div class=\"box i\">\n";
echo "          Bassicarella Architectes, Dubai, UAE Museum\n";
echo "        </div>\n";
echo "\n";
echo "\n";
echo "        <!--   section 4-->\n";
echo "        <div class=\"box j\">\n";
echo "          <img  src = \"https://content.codecademy.com/courses/learn-css-grid/project-iii/media/pexels-4.jpg\">\n";
echo "        </div>\n";
echo "        <div class=\"box k title\">\n";
echo "          Healing House Path\n";
echo "        </div>\n";
echo "        <div class=\"box l\">\n";
echo "          Bassicarella Architectes,\n";
echo "          Beijing, China\n";
echo "          Temple\n";
echo "        </div>\n";
echo "\n";
echo "        <!--   section 5-->\n";
echo "        <div class=\"box m\">\n";
echo "          <img  src = \"https://content.codecademy.com/courses/learn-css-grid/project-iii/media/pexels-5.jpg\">\n";
echo "        </div>\n";
echo "        <div class=\"box n title\">\n";
echo "          Curved Perfection\n";
echo "        </div>\n";
echo "        <div class=\"box o\">\n";
echo "          Bassicarella Architectes,\n";
echo "          Buenos Aires, Argentina\n";
echo "          Condominium\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "  </body>\n";
echo "\n";
echo "</html>";

?>
